from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ACTIONS = ("cleanup-drafts", "rebuild-wiki", "archive-stale")
STALE_DAYS = 30


@dataclass(frozen=True)
class PlannedChange:
    kind: str
    source: str | None
    target: str
    description: str
    backup: str | None = None


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _action_id(action: str) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    return f"{stamp}-{action}"


def _relative(root: Path, path: Path) -> str:
    return str(path.resolve().relative_to(root.resolve())).replace("\\", "/")


def _within(root: Path, path: Path) -> Path:
    resolved_root = root.resolve()
    resolved_path = path.resolve()
    try:
        resolved_path.relative_to(resolved_root)
    except ValueError as exc:
        raise ValueError(f"Refusing to operate outside workspace: {path}") from exc
    return resolved_path


def _actions_dir(root: Path) -> Path:
    return root / ".brain" / "actions"


def _archive_target(root: Path, action_id: str, category: str, source: Path) -> Path:
    rel = _relative(root, source)
    return _actions_dir(root) / "archive" / action_id / category / rel


def _backup_target(root: Path, action_id: str, source: Path) -> Path:
    rel = _relative(root, source)
    return _actions_dir(root) / "backups" / action_id / rel


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _draft_files(root: Path) -> list[Path]:
    drafts = root / "drafts"
    if not drafts.exists():
        return []
    return sorted(path for path in drafts.rglob("*") if path.is_file())


def _stale_processed_files(root: Path, *, now: datetime | None = None) -> list[Path]:
    processed = root / "processed"
    if not processed.exists():
        return []
    current = now or datetime.now(timezone.utc)
    stale = []
    for path in sorted(processed.rglob("*")):
        if not path.is_file():
            continue
        modified = datetime.fromtimestamp(path.stat().st_mtime, timezone.utc)
        if (current - modified).days >= STALE_DAYS:
            stale.append(path)
    return stale


def _raw_files(root: Path) -> list[Path]:
    raw = root / "raw"
    if not raw.exists():
        return []
    return sorted(path for path in raw.rglob("*") if path.is_file())


def _wiki_index_content(root: Path, files: list[Path]) -> str:
    lines = [
        "# ABW Source Index",
        "",
        "Status: generated_candidate",
        "",
        "This note was generated by `abw apply rebuild-wiki` as a safe source map. It does not claim grounded summaries.",
        "",
        "## Raw Sources",
        "",
    ]
    if not files:
        lines.append("- No raw sources found.")
    else:
        for path in files:
            lines.append(f"- `{_relative(root, path)}`")
    lines.append("")
    return "\n".join(lines)


def _plan_cleanup_drafts(root: Path, action_id: str) -> tuple[list[Path], list[PlannedChange]]:
    files = _draft_files(root)
    changes = [
        PlannedChange(
            kind="move",
            source=_relative(root, path),
            target=_relative(root, _archive_target(root, action_id, "drafts", path)),
            description="archive draft without deleting it",
        )
        for path in files
    ]
    return files, changes


def _plan_archive_stale(root: Path, action_id: str) -> tuple[list[Path], list[PlannedChange]]:
    files = _stale_processed_files(root)
    changes = [
        PlannedChange(
            kind="move",
            source=_relative(root, path),
            target=_relative(root, _archive_target(root, action_id, "processed", path)),
            description=f"archive processed file older than {STALE_DAYS} days",
        )
        for path in files
    ]
    return files, changes


def _plan_rebuild_wiki(root: Path, action_id: str) -> tuple[list[Path], list[PlannedChange]]:
    raw_files = _raw_files(root)
    target = root / "wiki" / "_abw_source_index.md"
    backup = _backup_target(root, action_id, target) if target.exists() else None
    change = PlannedChange(
        kind="write",
        source=None,
        target=_relative(root, target),
        backup=_relative(root, backup) if backup else None,
        description="write generated wiki source index from raw file names",
    )
    affected = [target]
    if backup:
        affected.append(backup)
    return affected, [change]


def _build_plan(root: Path, action: str, action_id: str) -> tuple[list[Path], list[PlannedChange], str]:
    if action == "cleanup-drafts":
        files, changes = _plan_cleanup_drafts(root, action_id)
        return files, changes, "low"
    if action == "archive-stale":
        files, changes = _plan_archive_stale(root, action_id)
        return files, changes, "medium"
    if action == "rebuild-wiki":
        files, changes = _plan_rebuild_wiki(root, action_id)
        return files, changes, "medium"
    raise ValueError(f"Unknown apply action: {action}")


def _move_file(root: Path, source_rel: str, target_rel: str) -> None:
    source = _within(root, root / source_rel)
    target = _within(root, root / target_rel)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(source), str(target))


def _copy_backup(root: Path, source: Path, backup_rel: str) -> None:
    backup = _within(root, root / backup_rel)
    backup.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, backup)


def _apply_changes(root: Path, action: str, action_id: str, changes: list[PlannedChange]) -> list[dict[str, Any]]:
    operations = []
    if action == "rebuild-wiki":
        raw_files = _raw_files(root)
        content = _wiki_index_content(root, raw_files)
        for change in changes:
            target = _within(root, root / change.target)
            existed = target.exists()
            if existed and change.backup:
                _copy_backup(root, target, change.backup)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            operations.append(
                {
                    "kind": "write",
                    "target": change.target,
                    "backup": change.backup,
                    "previously_existed": existed,
                }
            )
        return operations

    for change in changes:
        if not change.source:
            continue
        _move_file(root, change.source, change.target)
        operations.append({"kind": "move", "source": change.source, "target": change.target})
    return operations


def run_apply(workspace: str | Path = ".", action: str = "", *, yes: bool = False) -> dict[str, Any]:
    root = Path(workspace).resolve()
    if action not in ACTIONS:
        raise ValueError(f"Unknown apply action: {action}")

    action_id = _action_id(action)
    dry_run = not yes
    affected_paths, planned_changes, risk = _build_plan(root, action, action_id)
    planned = [change.__dict__ for change in planned_changes]
    operations: list[dict[str, Any]] = []
    if yes:
        operations = _apply_changes(root, action, action_id, planned_changes)

    rollback_possible = bool(planned_changes) and action in ACTIONS
    report = {
        "action_id": action_id,
        "workspace": str(root),
        "action": action,
        "mode": "apply" if yes else "dry-run",
        "dry_run": dry_run,
        "generated_at": _utc_now(),
        "files_affected": [_relative(root, path) for path in affected_paths],
        "files_affected_count": len(affected_paths),
        "changes_planned": planned,
        "changes_planned_count": len(planned_changes),
        "changes_applied": operations,
        "changes_applied_count": len(operations),
        "risk_level": risk,
        "rollback_possible": rollback_possible,
        "rollback_command": f"abw apply rollback {action_id} --yes" if rollback_possible and yes else None,
        "log_path": str((_actions_dir(root) / f"{action_id}.json").resolve()),
    }
    _write_json(Path(report["log_path"]), report)
    return report


def run_rollback(workspace: str | Path = ".", action_id: str = "", *, yes: bool = False) -> dict[str, Any]:
    root = Path(workspace).resolve()
    log_path = _actions_dir(root) / f"{action_id}.json"
    manifest = _read_json(log_path)
    operations = manifest.get("changes_applied") if isinstance(manifest.get("changes_applied"), list) else []
    rollback_id = _action_id(f"rollback-{action_id}")
    dry_run = not yes
    planned = []

    for operation in reversed(operations):
        if not isinstance(operation, dict):
            continue
        kind = operation.get("kind")
        if kind == "move":
            planned.append(
                {
                    "kind": "move",
                    "source": operation.get("target"),
                    "target": operation.get("source"),
                    "description": "restore archived file to original path",
                }
            )
        elif kind == "write":
            target = operation.get("target")
            backup = operation.get("backup")
            previously_existed = bool(operation.get("previously_existed"))
            planned.append(
                {
                    "kind": "restore" if previously_existed else "archive-created",
                    "source": backup or target,
                    "target": target,
                    "description": "restore previous file content" if previously_existed else "archive generated file",
                }
            )

    applied = []
    if yes:
        for item in planned:
            kind = item["kind"]
            source_rel = str(item["source"] or "")
            target_rel = str(item["target"] or "")
            if kind == "move":
                _move_file(root, source_rel, target_rel)
                applied.append(item)
            elif kind == "restore":
                source = _within(root, root / source_rel)
                target = _within(root, root / target_rel)
                current_archive = _archive_target(root, rollback_id, "replaced", target)
                if target.exists():
                    current_archive.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(target), str(current_archive))
                shutil.copy2(source, target)
                applied.append({**item, "current_archived_to": _relative(root, current_archive)})
            elif kind == "archive-created":
                target = _within(root, root / target_rel)
                created_archive = _archive_target(root, rollback_id, "created", target)
                if target.exists():
                    created_archive.parent.mkdir(parents=True, exist_ok=True)
                    shutil.move(str(target), str(created_archive))
                    applied.append({**item, "created_archived_to": _relative(root, created_archive)})

    report = {
        "action_id": rollback_id,
        "workspace": str(root),
        "action": "rollback",
        "rollback_of": action_id,
        "mode": "apply" if yes else "dry-run",
        "dry_run": dry_run,
        "generated_at": _utc_now(),
        "files_affected": [str(item.get("target") or "") for item in planned],
        "files_affected_count": len(planned),
        "changes_planned": planned,
        "changes_planned_count": len(planned),
        "changes_applied": applied,
        "changes_applied_count": len(applied),
        "risk_level": "medium" if planned else "low",
        "rollback_possible": False,
        "rollback_command": None,
        "log_path": str((_actions_dir(root) / f"{rollback_id}.json").resolve()),
    }
    _write_json(Path(report["log_path"]), report)
    return report


def render_apply_report(report: dict[str, Any]) -> str:
    lines = [
        "ABW Apply",
        "---------",
        f"Workspace: {report['workspace']}",
        f"Action: {report['action']}",
        f"Mode: {report['mode']}",
        f"Risk: {report['risk_level']}",
        f"Files affected: {report['files_affected_count']}",
        f"Changes planned: {report['changes_planned_count']}",
        f"Rollback possible: {'yes' if report.get('rollback_possible') else 'no'}",
        f"Operation log: {report['log_path']}",
    ]
    if report.get("rollback_command"):
        lines.append(f"Rollback command: {report['rollback_command']}")
    changes = report.get("changes_planned") or []
    if changes:
        lines.append("")
        lines.append("Plan:")
        for change in changes:
            source = change.get("source")
            target = change.get("target")
            if source:
                lines.append(f"- {change.get('description')}: {source} -> {target}")
            else:
                lines.append(f"- {change.get('description')}: {target}")
    return "\n".join(lines)
